spring:
  appication:
    name: madang

  datasource:
    url: jdbc:mariadb://localhost/madang_spring
    username: root
    password: green502

mybatis:
  mapper-locations: mappers/**/*.xml

springdoc:
  api-docs:
    version: openapi_3_1
  swagger-ui:
    default-model-expand-depth: -1
    default-models-expand-depth: -1
    path: /swagger
